language: go

go:
  - 1.6

env:
  global:
    - ENCRYPTION_LABEL: 6004e94fbaa2
    - COMMIT_AUTHOR_EMAIL: hello@devcows.com

install:
  - go get -v github.com/spf13/hugo
  - pip install Pygments --user

before_script:
  - mkdir themes
  - git clone --depth 1 https://github.com/devcows/hugo-universal-theme.git themes/hugo-universal-theme/

script:
  - hugo

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./deploy.sh
  on:
    branch: master

notifications:
  slack:
    rooms:
      - devcows:IbnfFBWkIVRwQBDuzYyfl5ZW#general
