language: go

go:
  - 1.6

install:
  - go get -v github.com/spf13/hugo
  - pip install Pygments --user

before_script:
  - mkdir themes
  - git clone --depth 1 https://github.com/halogenica/beautifulhugo themes/beautifulhugo/

script:
  - hugo
