language: go

go:
  - 1.6

env:
  global:
  - ENCRYPTION_LABEL: 6004e94fbaa2
  - COMMIT_AUTHOR_EMAIL: hello@devcows.com

install:
  - go get -v github.com/spf13/hugo
  - pip install Pygments --user

before_script:
  - mkdir themes
  - git clone --depth 1 https://github.com/halogenica/beautifulhugo themes/beautifulhugo/

script:
  - hugo

deploy: bash ./deploy.sh
