---
baseurl: "devcows.com"
languageCode: "en-us"
title: "DevCows"
theme: "universal"
MetaDataFormat: "yaml"
copyright: "Copyright (c) 2015 - 2016, DevCows; all rights reserved."
pygmentsUseClasses: true
PygmentsCodeFences: true
Paginate: 10

author:
  name: "DevCows"
  email: "hello@devcows.com"
  github: "devcows"

taxonomies:
  tag: "tags"
  category: "categories"

# permalinks:
#   post: /blog/:year/:month/:title/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Blog"
      url: "/post"
      weight: 2

params:
  logo: "/media/devcows-logo.png"
  subtitle: "Everything as Code"
  widgets:
    tags: true
    categories: true

# make tags and categories work
# indexes:
#   tag: "tags"
#   category: "categories"
